services:
  api-solid-pg:
    image: bitnami/postgresql
    ports:
      - "5433:5432"
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=apisolid
    volumes:
      - postgres_data:/bitnami/postgresql/data

volumes:
  postgres_data: